classes:
  - service.docker.client
parameters:
  _param:
    docker_image_compose: docker/compose:1.8.0
  docker:
    client:
      enabled: true
      compose:
        source:
          engine: docker
          image: ${_param:docker_image_compose}
